name: Publish to Chrome Web Store

on:
    release:
        types: [published] # triggers when a release is published manually

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.release.tag_name }}
                fetch-depth: 0
            
            - name: Create ZIP file
              run: |
                if [ ! -d src ]; then
                  echo "src directory not found"
                  exit 1
                fi
                cd src
                zip -r ../scrum-helper.zip . >/dev/null
                echo "Created zip:"
                unzip -l ../scrum-helper.zip
                if unzip -l ../scrum-helper.zip | awk '{print $4}' | grep -q '^manifest.json$'; then
                  echo "manifest.json is at zip root"
                else
                  echo "ERROR: manifest.json NOT at zip root; zip will fail on Chrome Web Store"
                  exit 1
                fi

            - name: Upload and Publish to Chrome Web Store
              uses: PlasmoHQ/chrome-extension@v3
              with:
                client_id: ${{ secrets.CHROME_CLIENT_ID }}
                client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
                refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
                extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
                zip: scrum-helper.zip
                publish: true