name: Publish to Chrome Web Store

on:
  workflow_dispatch: #This allows the worklfow to be triggered manually

jobs:
  pubish:
    name: Publish Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Create ZIP file
        run: |
          cd src
          zip -r ../extensionn.zip . -x "*.DS_Store"
        # This command zips the contents of src directory

      - name: Upload to Chrome Web Store
        uses: w3c/chrome-webstore-upload-action@v1
        with:
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          zip-file: extension.zip
