name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Draft Release
        id: release_drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug release-drafter outputs (safe)
        run: |
          printf 'release-drafter.tag_name=%s\n' "${{ steps.release_drafter.outputs.tag_name }}"
          echo 'release-drafter.body:'
          printf '%s\n' "${{ steps.release_drafter.outputs.body }}" > /tmp/release_drafter_body.txt
          echo "Wrote release body to /tmp/release_drafter_body.txt"

      - name: Create / prepend CHANGELOG entry
        if: steps.release_drafter.outputs.tag_name != ''
        run: |
          TAG="${{ steps.release_drafter.outputs.tag_name }}"
          BODY_FILE="/tmp/release_drafter_body.txt"
          DATE="$(date +%F)"
          if [ -f "$BODY_FILE" ]; then
            BODY="$(cat "$BODY_FILE")"
          else
            BODY="${{ steps.release_drafter.outputs.body }}"
          fi
          printf "## %s - %s\n\n%s\n\n---\n\n" "$TAG" "$DATE" "$BODY" > /tmp/new_changelog.md
          if [ -f CHANGELOG.md ]; then
            cat CHANGELOG.md >> /tmp/new_changelog.md
          fi
          mv /tmp/new_changelog.md CHANGELOG.md
          git status --porcelain || true

      - name: Commit & push CHANGELOG and tag via GITHUB_TOKEN
        if: steps.release_drafter.outputs.tag_name != ''
        env:
          TAG: ${{ steps.release_drafter.outputs.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add CHANGELOG.md || true

          if git diff --cached --quiet; then
            echo "No CHANGELOG.md changes to commit"
          else
            git commit -m "docs(changelog): update for ${TAG}"
          fi

          REPO="${{ github.repository }}"

          # Push commit (use token to authenticate)
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" HEAD:refs/heads/master

          # Create annotated tag if missing and push it
          if git rev-parse "${TAG}" >/dev/null 2>&1; then
            echo "Tag ${TAG} already exists locally"
          else
            git tag -a "${TAG}" -m "Release ${TAG}" || true
          fi
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" "refs/tags/${TAG}" || echo "Tag push failed or tag exists"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: (Optional) Update Changelog formatting / run scripts
        run: |
          # placeholder for any project-specific changelog formatting commands
          echo "Changelog updated; no additional formatting configured"